
"""
类型存根文件 - 为 C++ 扩展提供代码补全和类型提示
"""

# from typing import overload, List, Tuple

# class MonopoleImpedance:
#     def __init__(self, filename: str, scale: float = 1.0) -> None: ...
#     @overload
#     def __call__(self, freq_query: float) -> complex: ...
#     @overload
#     def __call__(self, freq_queries: List[float]) -> List[complex]: ...

# class MonopoleWakefield:
#     def __init__(self, filename: str, scale: float = 1.0) -> None: ...
#     @overload
#     def __call__(self, z_query: float) -> float: ...
#     @overload
#     def __call__(self, z_queries: List[float]) -> List[float]: ...

# class DipoleImpedance:
#     def __init__(self, filename: str, twiss_beta: float = 1.0, scale: float = 1.0) -> None: ...
#     @overload
#     def __call__(self, freq_query: float) -> complex: ...
#     @overload
#     def __call__(self, freq_queries: List[float]) -> List[complex]: ...

# class QuadrupoleImpedance:
#     def __init__(self, filename: str, twiss_beta: float = 1.0, scale: float = 1.0) -> None: ...
#     @overload
#     def __call__(self, freq_query: float) -> complex: ...
#     @overload
#     def __call__(self, freq_queries: List[float]) -> List[complex]: ...

# class DipoleWakefield:
#     def __init__(self, filename: str, twiss_beta: float = 1.0, scale: float = 1.0) -> None: ...
#     @overload
#     def __call__(self, z_query: float) -> float: ...
#     @overload
#     def __call__(self, z_queries: List[float]) -> List[float]: ...

# class QuadrupoleWakefield:
#     def __init__(self, filename: str, twiss_beta: float = 1.0, scale: float = 1.0) -> None: ...
#     @overload
#     def __call__(self, z_query: float) -> float: ...
#     @overload
#     def __call__(self, z_queries: List[float]) -> List[float]: ...

# __version__: str
# __cpp_available__: bool
# __all__: List[str]