# python/collective_effects/wakeimpe/longitudinal/__init__.pyi
from typing import overload, List

class MonopoleImpedance:
    def __init__(self, filename: str, scale: float = 1.0) -> None: ...
    def __init__(self, wakefield: MonopoleWakefield) -> None: ...
    @overload
    def __call__(self, freq_query: float) -> complex: ...
    @overload
    def __call__(self, freq_queries: List[float]) -> List[complex]: ...

class MonopoleWakefield:
    def __init__(self, filename: str, scale: float = 1.0) -> None: ...
    def __init__(self, impedance: MonopoleImpedance) -> None: ...
    @overload
    def __call__(self, z_query: float) -> float: ...
    @overload
    def __call__(self, z_queries: List[float]) -> List[float]: ...

__all__ = ["MonopoleImpedance", "MonopoleWakefield"]