# python/collective_effects/wakeimpe/transverse/__init__.pyi
from typing import overload, List

class DipoleImpedance:
    def __init__(self, filename: str, twiss_beta: float = 1.0, scale: float = 1.0) -> None: ...
    def __init__(self, wakefield: DipoleWakefield) -> None: ...
    @overload
    def __call__(self, freq_query: float) -> complex: ...
    @overload
    def __call__(self, freq_queries: List[float]) -> List[complex]: ...

class QuadrupoleImpedance:
    def __init__(self, filename: str, twiss_beta: float = 1.0, scale: float = 1.0) -> None: ...
    def __init__(self, wakefield: QuadrupoleWakefield) -> None: ...
    @overload
    def __call__(self, freq_query: float) -> complex: ...
    @overload
    def __call__(self, freq_queries: List[float]) -> List[complex]: ...

class DipoleWakefield:
    def __init__(self, filename: str, twiss_beta: float = 1.0, scale: float = 1.0) -> None: ...
    def __init__(self, impedance: DipoleImpedance) -> None: ...
    @overload
    def __call__(self, z_query: float) -> float: ...
    @overload
    def __call__(self, z_queries: List[float]) -> List[float]: ...

class QuadrupoleWakefield:
    def __init__(self, filename: str, twiss_beta: float = 1.0, scale: float = 1.0) -> None: ...
    def __init__(self, impedance: QuadrupoleImpedance) -> None: ...
    @overload
    def __call__(self, z_query: float) -> float: ...
    @overload
    def __call__(self, z_queries: List[float]) -> List[float]: ...

__all__ = ["DipoleImpedance", "QuadrupoleImpedance", "DipoleWakefield", "QuadrupoleWakefield"]